<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE us-patent-assignments [<!ELEMENT us-patent-assignments (action-key-code, transaction-date, patent-assignments)>
<!ATTLIST us-patent-assignments  dtd-version   CDATA  #IMPLIED
                                 date-produced CDATA  #IMPLIED>
<!ELEMENT action-key-code (#PCDATA)>
<!ELEMENT transaction-date (date)>
<!ELEMENT patent-assignments (data-available-code | patent-assignment+)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT data-available-code (#PCDATA)>
<!ELEMENT patent-assignment (assignment-record, patent-assignors, patent-assignees, patent-properties)>
<!ELEMENT assignment-record (reel-no, frame-no, last-update-date, purge-indicator, recorded-date, page-count?, correspondent, conveyance-text)>
<!ELEMENT patent-assignors (patent-assignor+)>
<!ELEMENT patent-assignees (patent-assignee+)>
<!ELEMENT patent-properties (patent-property+)>
<!ELEMENT reel-no (#PCDATA)>
<!ELEMENT frame-no (#PCDATA)>
<!ELEMENT last-update-date (date)>
<!ELEMENT purge-indicator (#PCDATA)>
<!ELEMENT recorded-date (date)>
<!ELEMENT page-count (#PCDATA)>
<!ELEMENT correspondent (name, address-1?, address-2?, address-3?, address-4?)>
<!ELEMENT conveyance-text (#PCDATA)>
<!ELEMENT patent-assignor (name, execution-date?, date-acknowledged?)>
<!ELEMENT patent-assignee (name, address-1?, address-2?, city?, state?, country-name?, postcode?)>
<!ELEMENT patent-property (document-id*, invention-title?)>
<!ELEMENT name (#PCDATA)>
<!ATTLIST name name-type (natural | legal)  #IMPLIED>
<!ELEMENT address-1 (#PCDATA)>
<!ELEMENT address-2 (#PCDATA)>
<!ELEMENT address-3 (#PCDATA)>
<!ELEMENT address-4 (#PCDATA)>
<!ELEMENT execution-date (date)>
<!ELEMENT date-acknowledged (date)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT country-name (#PCDATA)>
<!ELEMENT postcode (#PCDATA)>
<!ELEMENT document-id (country, doc-number, kind?, name?, date?)>
<!ELEMENT invention-title (#PCDATA | b | i | u | sup | sub)*>
<!ATTLIST invention-title  id   ID     #IMPLIED
                           lang CDATA  #REQUIRED>
<!ELEMENT country (#PCDATA)>
<!ELEMENT doc-number (#PCDATA)>
<!ELEMENT kind (#PCDATA)>
<!--bold formatting for text-->
<!ELEMENT b (#PCDATA | i | u | smallcaps)*>
<!--italic formatting for text-->
<!ELEMENT i (#PCDATA | b | u | smallcaps)*>
<!--underscore: style - single is default-->
<!ELEMENT u (#PCDATA | b | i | smallcaps)*>
<!ATTLIST u  style  (single | double | dash | dots )  'single' >
<!--superscripted text-->
<!ELEMENT sup (#PCDATA | b | u | i)*>
<!--subscripted text-->
<!ELEMENT sub (#PCDATA | b | u | i)*>
<!--small capitals-->
<!ELEMENT smallcaps (#PCDATA | b | u | i)*>
]>
<us-patent-assignments dtd-version="1.0" date-produced="20131101">
  <action-key-code>DA</action-key-code>
  <transaction-date>
    <date>20150727</date>
  </transaction-date>
  <patent-assignments>
    <patent-assignment>
      <assignment-record>
        <reel-no>19091</reel-no>
        <frame-no>278</frame-no>
        <last-update-date>
          <date>20150727</date>
        </last-update-date>
        <purge-indicator>Y</purge-indicator>
        <recorded-date>
          <date>20070320</date>
        </recorded-date>
        <page-count>4</page-count>
        <correspondent>
          <name>BRINKS HOFER GILSON &amp; LIONE</name>
          <address-1>P.O. BOX 10395</address-1>
          <address-2>CHICAGO, IL 60610</address-2>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>WEYER, LAWRENCE A.</name>
          <execution-date>
            <date>20070315</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>PAGE, ROBERT J.</name>
          <execution-date>
            <date>20070306</date>
          </execution-date>
        </patent-assignor>
        <patent-assignor>
          <name>OJJEH, BASSEL</name>
          <execution-date>
            <date>20070315</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>YAHOO! INC.</name>
          <address-1>701 FIRST AVENUE</address-1>
          <city>SUNNYVALE</city>
          <state>CALIFORNIA</state>
          <postcode>94089</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>11726014</doc-number>
            <kind>X0</kind>
            <date>20070320</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20130267033</doc-number>
            <kind>A1</kind>
            <date>20131010</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>9081044</doc-number>
            <kind>B2</kind>
            <date>20150714</date>
          </document-id>
          <invention-title lang="en">DETECTION CELL WITH CONTROLLED POWER DISSIPATION</invention-title>
        </patent-property>
      </patent-properties>
    </patent-assignment>
    <patent-assignment>
      <assignment-record>
        <reel-no>27379</reel-no>
        <frame-no>108</frame-no>
        <last-update-date>
          <date>20150727</date>
        </last-update-date>
        <purge-indicator>N</purge-indicator>
        <recorded-date>
          <date>20111214</date>
        </recorded-date>
        <page-count>9</page-count>
        <correspondent>
          <name>CANDICE ABREU</name>
          <address-1>555 FIFTH AVENUE</address-1>
          <address-2>C/O OSTROW KAUFMAN LLP</address-2>
          <address-3>NEW YORK, NY 10017</address-3>
        </correspondent>
        <conveyance-text>ASSIGNMENT OF ASSIGNORS INTEREST (SEE DOCUMENT FOR DETAILS).</conveyance-text>
      </assignment-record>
      <patent-assignors>
        <patent-assignor>
          <name>GOLDEN BRIDGE TECHNOLOGY</name>
          <execution-date>
            <date>20111115</date>
          </execution-date>
        </patent-assignor>
      </patent-assignors>
      <patent-assignees>
        <patent-assignee>
          <name>GOOGLE INC.</name>
          <address-1>1600 AMPHITHEATRE PARKWAY</address-1>
          <city>MOUNTAIN VIEW</city>
          <state>CALIFORNIA</state>
          <postcode>94043</postcode>
        </patent-assignee>
      </patent-assignees>
      <patent-properties>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>11976958</doc-number>
            <kind>X0</kind>
            <date>20071030</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20080063031</doc-number>
            <kind>A1</kind>
            <date>20080313</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>8548026</doc-number>
            <kind>B2</kind>
            <date>20131001</date>
          </document-id>
          <invention-title lang="en">Enhanced uplink packet transfer</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>12233176</doc-number>
            <kind>X0</kind>
            <date>20080918</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20090016273</doc-number>
            <kind>A1</kind>
            <date>20090115</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>7869404</doc-number>
            <kind>B2</kind>
            <date>20110111</date>
          </document-id>
          <invention-title lang="en">DEFERRED ACCESS METHOD FOR UPLINK PACKET CHANNEL</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>10935236</doc-number>
            <kind>X0</kind>
            <date>20040908</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>7436801</doc-number>
            <kind>B1</kind>
            <date>20081014</date>
          </document-id>
          <invention-title lang="en">DEFERRED ACCESS METHOD FOR UPLINK PACKET CHANNEL</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>10678648</doc-number>
            <kind>X0</kind>
            <date>20031006</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20040131106</doc-number>
            <kind>A1</kind>
            <date>20040708</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>7301988</doc-number>
            <kind>B2</kind>
            <date>20071127</date>
          </document-id>
          <invention-title lang="en">ENHANCED UPLINK PACKET TRANSFER</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>10144749</doc-number>
            <kind>X0</kind>
            <date>20020515</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>7099346</doc-number>
            <kind>B1</kind>
            <date>20060829</date>
          </document-id>
          <invention-title lang="en">CHANNEL CAPACITY OPTIMIZATION FOR PACKET SERVICES</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>10682985</doc-number>
            <kind>X0</kind>
            <date>20031014</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20040081115</doc-number>
            <kind>A1</kind>
            <date>20040429</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>7075971</doc-number>
            <kind>B2</kind>
            <date>20060711</date>
          </document-id>
          <invention-title lang="en">HYBRID DSMA/CDMA (DIGITAL SENSE MULTIPLE ACCESS/ CODE DIVISION MULTIPLE ACCESS) METHOD WITH COLLISION RESOLUTION FOR PACKET COMMUNICATIONS</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>10649816</doc-number>
            <kind>X0</kind>
            <date>20030828</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20040042429</doc-number>
            <kind>A1</kind>
            <date>20040304</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>7046717</doc-number>
            <kind>B2</kind>
            <date>20060516</date>
          </document-id>
          <invention-title lang="en">PRE-DATA POWER CONTROL COMMON PACKET CHANNEL</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09789958</doc-number>
            <kind>X0</kind>
            <date>20010222</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20030185286</doc-number>
            <kind>A1</kind>
            <date>20031002</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>7020184</doc-number>
            <kind>B2</kind>
            <date>20060328</date>
          </document-id>
          <invention-title lang="en">A STORE AND FORWARD HANDOFF</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09732186</doc-number>
            <kind>X0</kind>
            <date>20001208</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20010015997</doc-number>
            <kind>A1</kind>
            <date>20010823</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>7012907</doc-number>
            <kind>B2</kind>
            <date>20060314</date>
          </document-id>
          <invention-title lang="en">PACKET SPREAD-SPECTRUM RECEIVER</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>10667665</doc-number>
            <kind>X0</kind>
            <date>20030923</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20040057397</doc-number>
            <kind>A1</kind>
            <date>20040325</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6996155</doc-number>
            <kind>B2</kind>
            <date>20060207</date>
          </document-id>
          <invention-title lang="en">COMMON PACKET CHANNEL</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09970888</doc-number>
            <kind>X0</kind>
            <date>20011005</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20020015437</doc-number>
            <kind>A1</kind>
            <date>20020207</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6993065</doc-number>
            <kind>B2</kind>
            <date>20060131</date>
          </document-id>
          <invention-title lang="en">MULTI-CHANNEL SPREAD SPECTRUM SYSTEM</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09912452</doc-number>
            <kind>X0</kind>
            <date>20010726</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6983012</doc-number>
            <kind>B1</kind>
            <date>20060103</date>
          </document-id>
          <invention-title lang="en">IMPLEMENTATION OF DIGITAL FILTER WITH REDUCED HARDWARE</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>10083687</doc-number>
            <kind>X0</kind>
            <date>20020227</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20030026324</doc-number>
            <kind>A1</kind>
            <date>20030206</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6937641</doc-number>
            <kind>B2</kind>
            <date>20050830</date>
          </document-id>
          <invention-title lang="en">POWER-CONTROLLED RANDOM ACCESS</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09732185</doc-number>
            <kind>X0</kind>
            <date>20001208</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20010015996</doc-number>
            <kind>A1</kind>
            <date>20010823</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6894997</doc-number>
            <kind>B2</kind>
            <date>20050517</date>
          </document-id>
          <invention-title lang="en">PACKET SPREAD-SPECTRUM TRANSMITTER</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09793433</doc-number>
            <kind>X0</kind>
            <date>20010227</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20010009545</doc-number>
            <kind>A1</kind>
            <date>20010726</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6940841</doc-number>
            <kind>B2</kind>
            <date>20050906</date>
          </document-id>
          <invention-title lang="en">PACKET-SWITCHED SPREAD-SPECTRUM SYSTEM</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09854620</doc-number>
            <kind>X0</kind>
            <date>20010515</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6843597</doc-number>
            <kind>B1</kind>
            <date>20050118</date>
          </document-id>
          <invention-title lang="en">METHOD AND APPARATUS OF A FAST TWO-LOOP AUTOMATIC GAIN CONTROL CIRCUIT</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09662148</doc-number>
            <kind>X0</kind>
            <date>20000914</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6842480</doc-number>
            <kind>B1</kind>
            <date>20050111</date>
          </document-id>
          <invention-title lang="en">PROGRAMMABLE MATCHED FILTER BANK</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09598470</doc-number>
            <kind>X0</kind>
            <date>20000622</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6801569</doc-number>
            <kind>B1</kind>
            <date>20041005</date>
          </document-id>
          <invention-title lang="en">DIGITAL MATCHED FILTER BANK FOR OTHOGONAL SIGNAL SET</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09722685</doc-number>
            <kind>X0</kind>
            <date>20001128</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6757319</doc-number>
            <kind>B1</kind>
            <date>20040629</date>
          </document-id>
          <invention-title lang="en">CLOSED LOOP POWER CONTROL FOR COMMON DOWNLINK TRANSPORT CHANNELS</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09598469</doc-number>
            <kind>X0</kind>
            <date>20000622</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6741637</doc-number>
            <kind>B1</kind>
            <date>20040525</date>
          </document-id>
          <invention-title lang="en">METHOD AND APPARATUS OF JOINT DETECTION OF A CDMA RECEIVER</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09852085</doc-number>
            <kind>X0</kind>
            <date>20010510</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20010030997</doc-number>
            <kind>A1</kind>
            <date>20011018</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6714586</doc-number>
            <kind>B2</kind>
            <date>20040330</date>
          </document-id>
          <invention-title lang="en">SLIDING MATCHED FILTER WITH FLEXIBLE HARDWARE COMPLEXITY</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09695720</doc-number>
            <kind>X0</kind>
            <date>20001025</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6643318</doc-number>
            <kind>B1</kind>
            <date>20031104</date>
          </document-id>
          <invention-title lang="en">HYBRID DSMA/CDMA (DIGITAL SENSE MULTIPLE ACCESS/CODE DIVISION MULTIPLE ACCESS) METHOD WITH COLLISION RESOLUTION FOR PACKET COMMUNICATIONS</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>10096312</doc-number>
            <kind>X0</kind>
            <date>20020313</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20020136272</doc-number>
            <kind>A1</kind>
            <date>20020926</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6639936</doc-number>
            <kind>B2</kind>
            <date>20031028</date>
          </document-id>
          <invention-title lang="en">PRE-DATA POWER CONTROL COMMON PACKET CHANNEL</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09526867</doc-number>
            <kind>X0</kind>
            <date>20000316</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6631157</doc-number>
            <kind>B1</kind>
            <date>20031007</date>
          </document-id>
          <invention-title lang="en">MULTI-CLOCK MATCHED FILTER FOR RECEIVING SIGNALS WITH MULTIPATH</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09304345</doc-number>
            <kind>X0</kind>
            <date>19990504</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6606341</doc-number>
            <kind>B1</kind>
            <date>20030812</date>
          </document-id>
          <invention-title lang="en">COMMON PACKET CHANNEL WITH FIRMWARE HANDOFF</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09224722</doc-number>
            <kind>X0</kind>
            <date>19990104</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6587452</doc-number>
            <kind>B1</kind>
            <date>20030701</date>
          </document-id>
          <invention-title lang="en">HIGH PERFORMANCE SIGNAL STRUCTURE WITH MULTIPLE MODULATION FORMATS</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09466797</doc-number>
            <kind>X0</kind>
            <date>19991220</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6515981</doc-number>
            <kind>B1</kind>
            <date>20030204</date>
          </document-id>
          <invention-title lang="en">PACKET-SWITCHED SPREAD-SPECTRUM SYSTEM</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09778955</doc-number>
            <kind>X0</kind>
            <date>20010208</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>20010055293</doc-number>
            <kind>A1</kind>
            <date>20011227</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6507601</doc-number>
            <kind>B2</kind>
            <date>20030114</date>
          </document-id>
          <invention-title lang="en">COLLISION AVOIDANCE</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09722688</doc-number>
            <kind>X0</kind>
            <date>20001128</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6480525</doc-number>
            <kind>B1</kind>
            <date>20021112</date>
          </document-id>
          <invention-title lang="en">SECOND LEVEL COLLISION RESOLUTION FOR PACKET DATA COMMUNICATIONS</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09496352</doc-number>
            <kind>X0</kind>
            <date>20000202</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6400757</doc-number>
            <kind>B1</kind>
            <date>20020604</date>
          </document-id>
          <invention-title lang="en">SYMBOL-MATCHED FILTER HAVING A LOW SILICON AND POWER MANAGEMENT</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09182054</doc-number>
            <kind>X0</kind>
            <date>19981029</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6393049</doc-number>
            <kind>B1</kind>
            <date>20020521</date>
          </document-id>
          <invention-title lang="en">TWO-STAGE SYNCHRONIZATION OF SPREAD-SPECTRUM SIGNALS</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09275010</doc-number>
            <kind>X0</kind>
            <date>19990324</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6389056</doc-number>
            <kind>B1</kind>
            <date>20020514</date>
          </document-id>
          <invention-title lang="en">PRE-DATA POWER CONTROL COMMON PACKET CHANNEL</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09296508</doc-number>
            <kind>X0</kind>
            <date>19990422</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6349110</doc-number>
            <kind>B1</kind>
            <date>20020219</date>
          </document-id>
          <invention-title lang="en">SUBSYSTEM AND METHOD FOR COMBINING SPREAD-SPECTRUM MULTIPATH SINGNALS</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09668743</doc-number>
            <kind>X0</kind>
            <date>20000925</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6324210</doc-number>
            <kind>B1</kind>
            <date>20011127</date>
          </document-id>
          <invention-title lang="en">Sliding matched filter with flexible hardware complexity</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09570393</doc-number>
            <kind>X0</kind>
            <date>20000512</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6324209</doc-number>
            <kind>B1</kind>
            <date>20011127</date>
          </document-id>
          <invention-title lang="en">Multi-channel spread spectrum system</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09273507</doc-number>
            <kind>X0</kind>
            <date>19990322</date>
          </document-id>
          <document-id>
            <country>US</country>
            <doc-number>6324207</doc-number>
            <kind>B1</kind>
            <date>20011127</date>
          </document-id>
          <invention-title lang="en">HANDOFF WITH CLOSED-LOOP POWER CONTROL</invention-title>
        </patent-property>
        <patent-property>
          <document-id>
            <country>US</country>
            <doc-number>09605508</doc-number>
            <kind>X0</kind>
            <date>20000628</date>
          </document-id>
          <document-id>